INSERT INTO ur_ingest_session (
    ur_ingest_session_id, 
    device_id, 
    behavior_id, 
    behavior_json, 
    ingest_started_at, 
    ingest_finished_at, 
    session_agent, 
    elaboration
) VALUES (
    lower(hex(randomblob(16))), 
    lower(hex(randomblob(16))), 
    lower(hex(randomblob(16))),
    '{"extract_attachments": "uniform_resource"}',
    '2023-08-10 10:00:00', 
    '2023-08-10 11:30:00',
    '{"name": "Test Ingest Agent", "version": "1.0.0"}',
    '{}'
);

INSERT INTO ur_ingest_session_imap_account (
    ur_ingest_session_imap_account_id, 
    ingest_session_id, 
    email, 
    password, 
    host, 
    elaboration
) VALUES 
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
'john.doe@gmail.com', 'securePass2024!', 'imap.gmail.com', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
'jane.smith@yahoo.com', 'y4ho0S3cret!', 'imap.mail.yahoo.com', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
'robert.jones@outlook.com', 'Outlook123!', 'imap.outlook.com', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
'lucy.wang@company.com', 'Company#2024', 'imap.company.com', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
'ahmed.ali@aol.com', 'AolPass2024!', 'imap.aol.com', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
'claudia.martinez@icloud.com', 'iCloudSafe2024!', 'imap.mail.me.com', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
'david.kim@protonmail.com', 'Prot0nM@il!', 'imap.protonmail.com', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
'maria.gonzalez@zoho.com', 'Zoh0Secret2024!', 'imap.zoho.com', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
'paul.brown@fastmail.com', 'FastM@il2024!', 'imap.fastmail.com', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
'katya.novak@yandex.ru', 'YandexP@ss!', 'imap.yandex.com', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
'leo.muller@gmx.de', 'GmxStrongPass!', 'imap.gmx.com', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
'sean.connor@mail.com', 'M4ilSecret!', 'imap.mail.com', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
'grace.park@nate.com', 'NateSecure123!', 'imap.nate.com', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
'vikram.patel@rediffmail.com', 'R3diffMail!', 'imap.rediffmail.com', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
'laura.schmidt@web.de', 'WebD3Pass!', 'imap.web.de', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
'youssef.hassan@orange.fr', '0rangeFr2024!', 'imap.orange.fr', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
'sofia.rodriguez@bol.com.br', 'Bol123Brazil!', 'imap.bol.com.br', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
'francesco.rossi@libero.it', 'L1beroIt@ly!', 'imap.libero.it', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
'mei.chen@163.com', '163ChinaP@ss!', 'imap.163.com', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
'hassan.abdul@zimbra.com', 'Z1mbraP@ss!', 'imap.zimbra.com', '{}');


INSERT INTO ur_ingest_session_imap_acct_folder (
    ur_ingest_session_imap_acct_folder_id,
    ingest_session_id, 
    ingest_account_id, 
    folder_name, 
    elaboration
) VALUES 
-- Folders for john.doe@gmail.com
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com' ORDER BY created_at DESC LIMIT 1),
'Inbox', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com' ORDER BY created_at DESC LIMIT 1),
'Sent', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com' ORDER BY created_at DESC LIMIT 1),
'Drafts', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com' ORDER BY created_at DESC LIMIT 1),
'Spam', '{}'),

-- Folders for jane.smith@yahoo.com
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'jane.smith@yahoo.com' ORDER BY created_at DESC LIMIT 1),
'Inbox', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'jane.smith@yahoo.com' ORDER BY created_at DESC LIMIT 1),
'Sent', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'jane.smith@yahoo.com' ORDER BY created_at DESC LIMIT 1),
'Trash', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'jane.smith@yahoo.com' ORDER BY created_at DESC LIMIT 1),
'Archives', '{}'),

-- Folders for robert.jones@outlook.com
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'robert.jones@outlook.com' ORDER BY created_at DESC LIMIT 1),
'Inbox', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'robert.jones@outlook.com' ORDER BY created_at DESC LIMIT 1),
'Sent', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'robert.jones@outlook.com' ORDER BY created_at DESC LIMIT 1),
'Drafts', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'robert.jones@outlook.com' ORDER BY created_at DESC LIMIT 1),
'Important', '{}'),

-- Folders for lucy.wang@company.com
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'lucy.wang@company.com' ORDER BY created_at DESC LIMIT 1),
'Inbox', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'lucy.wang@company.com' ORDER BY created_at DESC LIMIT 1),
'Sent', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'lucy.wang@company.com' ORDER BY created_at DESC LIMIT 1),
'Trash', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'lucy.wang@company.com' ORDER BY created_at DESC LIMIT 1),
'Projects', '{}'),

-- Folders for ahmed.ali@aol.com
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'ahmed.ali@aol.com' ORDER BY created_at DESC LIMIT 1),
'Inbox', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'ahmed.ali@aol.com' ORDER BY created_at DESC LIMIT 1),
'Sent', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'ahmed.ali@aol.com' ORDER BY created_at DESC LIMIT 1),
'Trash', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'ahmed.ali@aol.com' ORDER BY created_at DESC LIMIT 1),
'Archive', '{}'),

-- Folders for claudia.martinez@icloud.com
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'claudia.martinez@icloud.com' ORDER BY created_at DESC LIMIT 1),
'Inbox', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'claudia.martinez@icloud.com' ORDER BY created_at DESC LIMIT 1),
'Sent', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'claudia.martinez@icloud.com' ORDER BY created_at DESC LIMIT 1),
'Trash', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'claudia.martinez@icloud.com' ORDER BY created_at DESC LIMIT 1),
'VIP', '{}'),

-- Folders for david.kim@protonmail.com
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'david.kim@protonmail.com' ORDER BY created_at DESC LIMIT 1),
'Inbox', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'david.kim@protonmail.com' ORDER BY created_at DESC LIMIT 1),
'Sent', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'david.kim@protonmail.com' ORDER BY created_at DESC LIMIT 1),
'Drafts', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'david.kim@protonmail.com' ORDER BY created_at DESC LIMIT 1),
'Spam', '{}'),

-- Folders for maria.gonzalez@zoho.com
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'maria.gonzalez@zoho.com' ORDER BY created_at DESC LIMIT 1),
'Inbox', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'maria.gonzalez@zoho.com' ORDER BY created_at DESC LIMIT 1),
'Sent', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'maria.gonzalez@zoho.com' ORDER BY created_at DESC LIMIT 1),
'Trash', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'maria.gonzalez@zoho.com' ORDER BY created_at DESC LIMIT 1),
'Archives', '{}'),

-- Folders for paul.brown@fastmail.com
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'paul.brown@fastmail.com' ORDER BY created_at DESC LIMIT 1),
'Inbox', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'paul.brown@fastmail.com' ORDER BY created_at DESC LIMIT 1),
'Sent', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'paul.brown@fastmail.com' ORDER BY created_at DESC LIMIT 1),
'Drafts', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'paul.brown@fastmail.com' ORDER BY created_at DESC LIMIT 1),
'Junk', '{}');


INSERT INTO ur_ingest_session_imap_acct_folder_message (
    ur_ingest_session_imap_acct_folder_message_id, 
    ingest_session_id, 
    ingest_imap_acct_folder_id,
    uniform_resource_id, 
    message, 
    message_id, 
    subject, 
    "from", 
    cc, 
    bcc, 
    status, 
    date, 
    email_references
) VALUES 
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Hey John, here is the report you asked for.', 'msg-0001', 'Monthly Report', 'manager@example.com', '[]', '[]', '["UNREAD"]', '2024-08-01', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Dont forget the meeting tomorrow at 9 AM.', 'msg-0002', 'Meeting Reminder', 'teamlead@example.com', '[]', '[]', '["UNREAD", "IMPORTANT"]', '2024-08-01', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com') ORDER BY created_at DESC LIMIT 1),
'attachment_resource_id_2', 'Please find the attached invoice.', 'msg-0003', 'Invoice August', 'billing@example.com', '[]', '[]', '["READ"]', '2024-08-01', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Happy Birthday, John! Wishing you all the best.', 'msg-0004', 'Happy Birthday!', 'friends@example.com', '["jane@example.com"]', '[]', '["UNREAD"]', '2024-08-02', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com') ORDER BY created_at DESC LIMIT 1),
'attachment_resource_id_3', 'Here is the project proposal.', 'msg-0005', 'Project Proposal', 'client@example.com', '[]', '[]', '["READ"]', '2024-08-02', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Please review the attached contract.', 'msg-0006', 'Contract Review', 'legal@example.com', '[]', '[]', '["UNREAD"]', '2024-08-03', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Can we reschedule our meeting?', 'msg-0007', 'Meeting Reschedule', 'colleague@example.com', '[]', '[]', '["UNREAD"]', '2024-08-04', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Please confirm your subscription.', 'msg-0008', 'Subscription Confirmation', 'newsletters@example.com', '[]', '[]', '["UNREAD", "PROMOTION"]', '2024-08-05', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'John, here is your weekly update.', 'msg-0009', 'Weekly Update', 'updates@example.com', '[]', '[]', '["READ"]', '2024-08-06', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Reminder: Your bill is due.', 'msg-0010', 'Billing Reminder', 'billing@example.com', '[]', '[]', '["UNREAD"]', '2024-08-06', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Your flight has been confirmed.', 'msg-0011', 'Flight Confirmation', 'travel@example.com', '[]', '[]', '["READ"]', '2024-08-07', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Invitation to the annual conference.', 'msg-0012', 'Conference Invitation', 'events@example.com', '[]', '[]', '["UNREAD"]', '2024-08-08', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Your account statement is ready.', 'msg-0013', 'Account Statement', 'bank@example.com', '[]', '[]', '["READ"]', '2024-08-08', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'New job opening in your area.', 'msg-0014', 'Job Opening', 'careers@example.com', '[]', '[]', '["UNREAD"]', '2024-08-09', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Thank you for your purchase.', 'msg-0015', 'Purchase Confirmation', 'store@example.com', '[]', '[]', '["READ"]', '2024-08-09', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Your subscription has been renewed.', 'msg-0016', 'Subscription Renewal', 'services@example.com', '[]', '[]', '["UNREAD"]', '2024-08-10', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Reminder: Doctors appointment on Monday.', 'msg-0017', 'Appointment Reminder', 'clinic@example.com', '[]', '[]', '["UNREAD", "IMPORTANT"]', '2024-08-11', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Your password has been reset.', 'msg-0018', 'Password Reset', 'support@example.com', '[]', '[]', '["READ"]', '2024-08-11', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'John, please review the attached document.', 'msg-0019', 'Document Review', 'colleague@example.com', '["boss@example.com"]', '[]', '["UNREAD"]', '2024-08-12', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Congratulations on your promotion!', 'msg-0020', 'Promotion', 'hr@example.com', '[]', '[]', '["READ"]', '2024-08-12', '[]');


INSERT INTO ur_ingest_session_imap_acct_folder_message (
    ur_ingest_session_imap_acct_folder_message_id, 
    ingest_session_id, 
    ingest_imap_acct_folder_id,
    uniform_resource_id, 
    message, 
    message_id, 
    subject, 
    "from", 
    cc, 
    bcc, 
    status, 
    date, 
    email_references
) VALUES 
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'jane.smith@yahoo.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Hi Jane, are you available for a quick call?', 'msg-0021', 'Quick Call', 'manager@yahoo.com', '[]', '[]', '["UNREAD"]', '2024-08-01', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'jane.smith@yahoo.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Please review the attached project timeline.', 'msg-0022', 'Project Timeline', 'teamlead@yahoo.com', '[]', '[]', '["UNREAD", "IMPORTANT"]', '2024-08-01', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'jane.smith@yahoo.com') ORDER BY created_at DESC LIMIT 1),
'attachment_resource_id_4', 'Jane, here is the document you requested.', 'msg-0023', 'Requested Document', 'colleague@yahoo.com', '[]', '[]', '["READ"]', '2024-08-01', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'jane.smith@yahoo.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Happy Friday! Any plans for the weekend?', 'msg-0024', 'Weekend Plans', 'friend@yahoo.com', '["another.friend@yahoo.com"]', '[]', '["UNREAD"]', '2024-08-02', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'jane.smith@yahoo.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Your Amazon order has shipped.', 'msg-0025', 'Order Shipped', 'amazon@yahoo.com', '[]', '[]', '["READ"]', '2024-08-02', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'jane.smith@yahoo.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Please find the attached quarterly report.', 'msg-0026', 'Quarterly Report', 'finance@yahoo.com', '[]', '[]', '["UNREAD"]', '2024-08-03', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'jane.smith@yahoo.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Can we move the deadline to next week?', 'msg-0027', 'Deadline Adjustment', 'project.manager@yahoo.com', '[]', '[]', '["UNREAD"]', '2024-08-04', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'jane.smith@yahoo.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Reminder: Your appointment is tomorrow.', 'msg-0028', 'Appointment Reminder', 'calendar@yahoo.com', '[]', '[]', '["UNREAD"]', '2024-08-05', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'jane.smith@yahoo.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Jane, dont miss this sale!', 'msg-0029', 'Exclusive Sale', 'marketing@yahoo.com', '[]', '[]', '["UNREAD", "PROMOTION"]', '2024-08-06', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'jane.smith@yahoo.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Weekly newsletter - August edition.', 'msg-0030', 'August Newsletter', 'newsletter@yahoo.com', '[]', '[]', '["READ"]', '2024-08-06', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'jane.smith@yahoo.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Security alert: New login to your account.', 'msg-0031', 'Security Alert', 'security@yahoo.com', '[]', '[]', '["UNREAD", "IMPORTANT"]', '2024-08-07', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'jane.smith@yahoo.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Thank you for your payment.', 'msg-0032', 'Payment Confirmation', 'billing@yahoo.com', '[]', '[]', '["READ"]', '2024-08-07', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'jane.smith@yahoo.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Reminder: Your subscription is about to expire.', 'msg-0033', 'Subscription Expiration', 'subscriptions@yahoo.com', '[]', '[]', '["UNREAD"]', '2024-08-08', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'jane.smith@yahoo.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Your account has been updated.', 'msg-0034', 'Account Update', 'support@yahoo.com', '[]', '[]', '["READ"]', '2024-08-09', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'jane.smith@yahoo.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Your parcel has been delivered.', 'msg-0035', 'Delivery Confirmation', 'shipping@yahoo.com', '[]', '[]', '["READ"]', '2024-08-09', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'jane.smith@yahoo.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Jane, your weekly digest is here.', 'msg-0036', 'Weekly Digest', 'digest@yahoo.com', '[]', '[]', '["READ"]', '2024-08-10', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'jane.smith@yahoo.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Important: Password change required.', 'msg-0037', 'Password Change Required', 'security@yahoo.com', '[]', '[]', '["UNREAD", "IMPORTANT"]', '2024-08-10', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'jane.smith@yahoo.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Invitation: Join us for the webinar.', 'msg-0038', 'Webinar Invitation', 'events@yahoo.com', '[]', '[]', '["UNREAD"]', '2024-08-11', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'jane.smith@yahoo.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Your insurance policy has been renewed.', 'msg-0039', 'Policy Renewal', 'insurance@yahoo.com', '[]', '[]', '["READ"]', '2024-08-11', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'jane.smith@yahoo.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Jane, your payment was successful.', 'msg-0040', 'Payment Success', 'billing@yahoo.com', '[]', '[]', '["READ"]', '2024-08-12', '[]');

INSERT INTO ur_ingest_session_imap_acct_folder_message (
    ur_ingest_session_imap_acct_folder_message_id, 
    ingest_session_id, 
    ingest_imap_acct_folder_id,
    uniform_resource_id, 
    message, 
    message_id, 
    subject, 
    "from", 
    cc, 
    bcc, 
    status, 
    date, 
    email_references
) VALUES 
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'robert.jones@outlook.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Hi Robert, please find attached the project brief.', 'msg-0041', 'Project Brief', 'project.manager@outlook.com', '[]', '[]', '["UNREAD"]', '2024-08-01', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'robert.jones@outlook.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Dont forget to submit your timesheet.', 'msg-0042', 'Timesheet Reminder', 'hr@outlook.com', '[]', '[]', '["UNREAD", "IMPORTANT"]', '2024-08-01', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'robert.jones@outlook.com') ORDER BY created_at DESC LIMIT 1),
'attachment_resource_id_5', 'Here is the invoice for July.', 'msg-0043', 'July Invoice', 'billing@outlook.com', '[]', '[]', '["READ"]', '2024-08-01', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'robert.jones@outlook.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Happy Anniversary, Robert! Enjoy your day.', 'msg-0044', 'Anniversary Wishes', 'wellwisher@outlook.com', '["family@outlook.com"]', '[]', '["UNREAD"]', '2024-08-02', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'robert.jones@outlook.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Your Microsoft subscription is expiring soon.', 'msg-0045', 'Subscription Expiry', 'microsoft@outlook.com', '[]', '[]', '["READ"]', '2024-08-02', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'robert.jones@outlook.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Robert, here is your weekly summary.', 'msg-0046', 'Weekly Summary', 'updates@outlook.com', '[]', '[]', '["UNREAD"]', '2024-08-03', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'robert.jones@outlook.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Can we reschedule our 1:1 meeting?', 'msg-0047', '1:1 Meeting Reschedule', 'teamlead@outlook.com', '[]', '[]', '["UNREAD"]', '2024-08-04', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'robert.jones@outlook.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Invitation: Join us for the Q3 webinar.', 'msg-0048', 'Q3 Webinar Invitation', 'events@outlook.com', '[]', '[]', '["UNREAD"]', '2024-08-05', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'robert.jones@outlook.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Robert, please complete the attached survey.', 'msg-0049', 'Customer Survey', 'survey@outlook.com', '[]', '[]', '["UNREAD"]', '2024-08-06', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'robert.jones@outlook.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Reminder: Your bill is due in 3 days.', 'msg-0050', 'Billing Reminder', 'billing@outlook.com', '[]', '[]', '["UNREAD"]', '2024-08-06', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'robert.jones@outlook.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Your booking has been confirmed.', 'msg-0051', 'Booking Confirmation', 'travel@outlook.com', '[]', '[]', '["READ"]', '2024-08-07', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'robert.jones@outlook.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Action Required: Please update your payment details.', 'msg-0052', 'Update Payment Details', 'billing@outlook.com', '[]', '[]', '["UNREAD", "IMPORTANT"]', '2024-08-08', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'robert.jones@outlook.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Robert, please review the attached contract.', 'msg-0053', 'Contract Review', 'legal@outlook.com', '[]', '[]', '["UNREAD"]', '2024-08-08', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'robert.jones@outlook.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Congratulations on your new role!', 'msg-0054', 'New Role Congratulations', 'hr@outlook.com', '[]', '[]', '["UNREAD"]', '2024-08-09', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'robert.jones@outlook.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'New device login detected.', 'msg-0055', 'Security Alert', 'security@outlook.com', '[]', '[]', '["UNREAD", "IMPORTANT"]', '2024-08-09', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'robert.jones@outlook.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Robert, your subscription has been renewed.', 'msg-0056', 'Subscription Renewal', 'subscriptions@outlook.com', '[]', '[]', '["UNREAD"]', '2024-08-10', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'robert.jones@outlook.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Your password has been reset successfully.', 'msg-0057', 'Password Reset Success', 'support@outlook.com', '[]', '[]', '["READ"]', '2024-08-11', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'robert.jones@outlook.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Robert, please review the attached presentation.', 'msg-0058', 'Presentation Review', 'colleague@outlook.com', '["boss@outlook.com"]', '[]', '["UNREAD"]', '2024-08-12', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'robert.jones@outlook.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Your parcel is out for delivery.', 'msg-0059', 'Parcel Out for Delivery', 'shipping@outlook.com', '[]', '[]', '["READ"]', '2024-08-12', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'robert.jones@outlook.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Congratulations, youve won a prize!', 'msg-0060', 'Prize Winner Notification', 'contests@outlook.com', '[]', '[]', '["UNREAD", "PROMOTION"]', '2024-08-12', '[]');


INSERT INTO ur_ingest_session_imap_acct_folder_message (
    ur_ingest_session_imap_acct_folder_message_id, 
    ingest_session_id, 
    ingest_imap_acct_folder_id,
    uniform_resource_id, 
    message, 
    message_id, 
    subject, 
    "from", 
    cc, 
    bcc, 
    status, 
    date, 
    email_references
) VALUES 
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'lucy.wang@company.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Hi Lucy, please find attached the contract.', 'msg-0061', 'Contract Attachment', 'legal@company.com', '[]', '[]', '["UNREAD"]', '2024-08-01', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'lucy.wang@company.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Please review the quarterly financials.', 'msg-0062', 'Quarterly Financials', 'finance@company.com', '[]', '[]', '["UNREAD", "IMPORTANT"]', '2024-08-01', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'lucy.wang@company.com') ORDER BY created_at DESC LIMIT 1),
'attachment_resource_id_6', 'Lucy, here is the report you requested.', 'msg-0063', 'Requested Report', 'colleague@company.com', '[]', '[]', '["READ"]', '2024-08-01', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'lucy.wang@company.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Please review the attached proposal.', 'msg-0064', 'Proposal Review', 'client@company.com', '["another.client@company.com"]', '[]', '["UNREAD"]', '2024-08-02', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'lucy.wang@company.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Your subscription has been renewed.', 'msg-0065', 'Subscription Renewal', 'subscriptions@company.com', '[]', '[]', '["READ"]', '2024-08-02', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'lucy.wang@company.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Reminder: Your meeting is tomorrow at 10 AM.', 'msg-0066', 'Meeting Reminder', 'calendar@company.com', '[]', '[]', '["UNREAD"]', '2024-08-03', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'lucy.wang@company.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Lucy, your order has been shipped.', 'msg-0067', 'Order Shipped', 'shipping@company.com', '[]', '[]', '["READ"]', '2024-08-04', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'lucy.wang@company.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Action Required: Please update your payment details.', 'msg-0068', 'Update Payment Details', 'billing@company.com', '[]', '[]', '["UNREAD", "IMPORTANT"]', '2024-08-05', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'lucy.wang@company.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Reminder: Your subscription is about to expire.', 'msg-0069', 'Subscription Expiration', 'subscriptions@company.com', '[]', '[]', '["UNREAD"]', '2024-08-06', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'lucy.wang@company.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Lucy, here is your weekly summary.', 'msg-0070', 'Weekly Summary', 'updates@company.com', '[]', '[]', '["UNREAD"]', '2024-08-06', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'lucy.wang@company.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Your package is out for delivery.', 'msg-0071', 'Package Out for Delivery', 'delivery@company.com', '[]', '[]', '["READ"]', '2024-08-07', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'lucy.wang@company.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Lucy, your flight details are confirmed.', 'msg-0072', 'Flight Confirmation', 'travel@company.com', '[]', '[]', '["READ"]', '2024-08-07', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'lucy.wang@company.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Congratulations on your promotion!', 'msg-0073', 'Promotion Congratulations', 'hr@company.com', '[]', '[]', '["UNREAD"]', '2024-08-08', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'lucy.wang@company.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Please review the attached document.', 'msg-0074', 'Document Review', 'legal@company.com', '[]', '[]', '["UNREAD"]', '2024-08-08', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'lucy.wang@company.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Security alert: New login from unknown device.', 'msg-0075', 'Security Alert', 'security@company.com', '[]', '[]', '["UNREAD", "IMPORTANT"]', '2024-08-09', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'lucy.wang@company.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Reminder: Your bill is due.', 'msg-0076', 'Billing Reminder', 'billing@company.com', '[]', '[]', '["UNREAD"]', '2024-08-09', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'lucy.wang@company.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Lucy, your appointment has been confirmed.', 'msg-0077', 'Appointment Confirmation', 'appointments@company.com', '[]', '[]', '["READ"]', '2024-08-10', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'lucy.wang@company.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Action Required: Update your security questions.', 'msg-0078', 'Update Security Questions', 'support@company.com', '[]', '[]', '["UNREAD", "IMPORTANT"]', '2024-08-10', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'lucy.wang@company.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Invitation: Join us for the company retreat.', 'msg-0079', 'Company Retreat Invitation', 'hr@company.com', '[]', '[]', '["UNREAD"]', '2024-08-11', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'lucy.wang@company.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Lucy, please complete the attached survey.', 'msg-0080', 'Survey Request', 'survey@company.com', '[]', '[]', '["READ"]', '2024-08-12', '[]');

INSERT INTO ur_ingest_session_imap_acct_folder_message (
    ur_ingest_session_imap_acct_folder_message_id, 
    ingest_session_id, 
    ingest_imap_acct_folder_id,
    uniform_resource_id, 
    message, 
    message_id, 
    subject, 
    "from", 
    cc, 
    bcc, 
    status, 
    date, 
    email_references
) VALUES 
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'david.lee@enterprise.org') ORDER BY created_at DESC LIMIT 1),
NULL, 'Hi David, the quarterly meeting is scheduled for next Monday.', 'msg-0081', 'Quarterly Meeting', 'hr@enterprise.org', '[]', '[]', '["UNREAD"]', '2024-08-01', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'david.lee@enterprise.org') ORDER BY created_at DESC LIMIT 1),
NULL, 'Please review the attached client feedback.', 'msg-0082', 'Client Feedback', 'customer.service@enterprise.org', '[]', '[]', '["UNREAD", "IMPORTANT"]', '2024-08-02', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'david.lee@enterprise.org') ORDER BY created_at DESC LIMIT 1),
'attachment_resource_id_7', 'Here is the budget report for your review.', 'msg-0083', 'Budget Report', 'finance@enterprise.org', '[]', '[]', '["READ"]', '2024-08-02', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'david.lee@enterprise.org') ORDER BY created_at DESC LIMIT 1),
NULL, 'David, dont miss this company event!', 'msg-0084', 'Company Event', 'events@enterprise.org', '["colleague1@enterprise.org"]', '[]', '["UNREAD"]', '2024-08-03', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'david.lee@enterprise.org') ORDER BY created_at DESC LIMIT 1),
NULL, 'Your security training is overdue.', 'msg-0085', 'Security Training Overdue', 'security@enterprise.org', '[]', '[]', '["UNREAD", "IMPORTANT"]', '2024-08-04', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'david.lee@enterprise.org') ORDER BY created_at DESC LIMIT 1),
NULL, 'Can we move our 1:1 meeting to tomorrow?', 'msg-0086', '1:1 Meeting Reschedule', 'manager@enterprise.org', '[]', '[]', '["READ"]', '2024-08-05', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'david.lee@enterprise.org') ORDER BY created_at DESC LIMIT 1),
NULL, 'Invitation to join the new project.', 'msg-0087', 'Project Invitation', 'project.lead@enterprise.org', '[]', '[]', '["UNREAD"]', '2024-08-06', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'david.lee@enterprise.org') ORDER BY created_at DESC LIMIT 1),
NULL, 'David, your timesheet is due today.', 'msg-0088', 'Timesheet Reminder', 'hr@enterprise.org', '[]', '[]', '["READ"]', '2024-08-07', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'david.lee@enterprise.org') ORDER BY created_at DESC LIMIT 1),
NULL, 'Your leave request has been approved.', 'msg-0089', 'Leave Approval', 'hr@enterprise.org', '[]', '[]', '["UNREAD"]', '2024-08-07', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'david.lee@enterprise.org') ORDER BY created_at DESC LIMIT 1),
NULL, 'Your expense report for July has been processed.', 'msg-0090', 'Expense Report Processed', 'finance@enterprise.org', '[]', '[]', '["READ"]', '2024-08-08', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'david.lee@enterprise.org') ORDER BY created_at DESC LIMIT 1),
NULL, 'David, please review the attached proposal.', 'msg-0091', 'Proposal Review', 'client@enterprise.org', '[]', '[]', '["UNREAD"]', '2024-08-09', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'david.lee@enterprise.org') ORDER BY created_at DESC LIMIT 1),
NULL, 'Your password has been reset successfully.', 'msg-0092', 'Password Reset Success', 'it.support@enterprise.org', '[]', '[]', '["READ"]', '2024-08-09', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'david.lee@enterprise.org') ORDER BY created_at DESC LIMIT 1),
NULL, 'David, your performance review is scheduled for next week.', 'msg-0093', 'Performance Review', 'hr@enterprise.org', '["manager@enterprise.org"]', '[]', '["UNREAD"]', '2024-08-10', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'david.lee@enterprise.org') ORDER BY created_at DESC LIMIT 1),
NULL, 'Please update your contact information.', 'msg-0094', 'Update Contact Information', 'hr@enterprise.org', '[]', '[]', '["UNREAD"]', '2024-08-10', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'david.lee@enterprise.org') ORDER BY created_at DESC LIMIT 1),
NULL, 'David, your order has been delivered.', 'msg-0095', 'Order Delivered', 'shipping@enterprise.org', '[]', '[]', '["READ"]', '2024-08-11', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'david.lee@enterprise.org') ORDER BY created_at DESC LIMIT 1),
NULL, 'Congratulations on your work anniversary!', 'msg-0096', 'Work Anniversary Congratulations', 'hr@enterprise.org', '[]', '[]', '["UNREAD"]', '2024-08-12', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'david.lee@enterprise.org') ORDER BY created_at DESC LIMIT 1),
NULL, 'David, your feedback is important to us.', 'msg-0097', 'Feedback Request', 'survey@enterprise.org', '[]', '[]', '["READ"]', '2024-08-12', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'david.lee@enterprise.org') ORDER BY created_at DESC LIMIT 1),
NULL, 'Please review the attached contract.', 'msg-0098', 'Contract Review', 'legal@enterprise.org', '[]', '[]', '["UNREAD"]', '2024-08-12', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'david.lee@enterprise.org') ORDER BY created_at DESC LIMIT 1),
NULL, 'Security alert: Unusual login activity detected.', 'msg-0099', 'Security Alert', 'it.support@enterprise.org', '[]', '[]', '["UNREAD", "IMPORTANT"]', '2024-08-13', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'david.lee@enterprise.org') ORDER BY created_at DESC LIMIT 1),
NULL, 'David, please complete the attached survey.', 'msg-0100', 'Survey Completion', 'survey@enterprise.org', '[]', '[]', '["READ"]', '2024-08-14', '[]');
