INSERT INTO ur_ingest_session (
    ur_ingest_session_id, 
    device_id, 
    behavior_id, 
    behavior_json, 
    ingest_started_at, 
    ingest_finished_at, 
    session_agent, 
    elaboration
) VALUES (
    lower(hex(randomblob(16))), 
    lower(hex(randomblob(16))), 
    lower(hex(randomblob(16))),
    '{"extract_attachments": "uniform_resource"}',
    '2023-08-10 10:00:00', 
    '2023-08-10 11:30:00',
    '{"name": "Test Ingest Agent", "version": "1.0.0"}',
    '{}'
);

INSERT INTO ur_ingest_session_imap_account (
    ur_ingest_session_imap_account_id, 
    ingest_session_id, 
    email, 
    password, 
    host, 
    elaboration
) VALUES 
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
'john.doe@gmail.com', 'securePass2024!', 'imap.gmail.com', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
'jane.smith@yahoo.com', 'y4ho0S3cret!', 'imap.mail.yahoo.com', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
'robert.jones@outlook.com', 'Outlook123!', 'imap.outlook.com', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
'lucy.wang@company.com', 'Company#2024', 'imap.company.com', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
'ahmed.ali@aol.com', 'AolPass2024!', 'imap.aol.com', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
'claudia.martinez@icloud.com', 'iCloudSafe2024!', 'imap.mail.me.com', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
'david.kim@protonmail.com', 'Prot0nM@il!', 'imap.protonmail.com', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
'maria.gonzalez@zoho.com', 'Zoh0Secret2024!', 'imap.zoho.com', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
'paul.brown@fastmail.com', 'FastM@il2024!', 'imap.fastmail.com', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
'katya.novak@yandex.ru', 'YandexP@ss!', 'imap.yandex.com', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
'leo.muller@gmx.de', 'GmxStrongPass!', 'imap.gmx.com', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
'sean.connor@mail.com', 'M4ilSecret!', 'imap.mail.com', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
'grace.park@nate.com', 'NateSecure123!', 'imap.nate.com', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
'vikram.patel@rediffmail.com', 'R3diffMail!', 'imap.rediffmail.com', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
'laura.schmidt@web.de', 'WebD3Pass!', 'imap.web.de', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
'youssef.hassan@orange.fr', '0rangeFr2024!', 'imap.orange.fr', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
'sofia.rodriguez@bol.com.br', 'Bol123Brazil!', 'imap.bol.com.br', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
'francesco.rossi@libero.it', 'L1beroIt@ly!', 'imap.libero.it', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
'mei.chen@163.com', '163ChinaP@ss!', 'imap.163.com', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
'hassan.abdul@zimbra.com', 'Z1mbraP@ss!', 'imap.zimbra.com', '{}');


INSERT INTO ur_ingest_session_imap_acct_folder (
    ur_ingest_session_imap_acct_folder_id,
    ingest_session_id, 
    ingest_account_id, 
    folder_name, 
    elaboration
) VALUES 
-- Folders for john.doe@gmail.com
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com' ORDER BY created_at DESC LIMIT 1),
'Inbox', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com' ORDER BY created_at DESC LIMIT 1),
'Sent', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com' ORDER BY created_at DESC LIMIT 1),
'Drafts', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com' ORDER BY created_at DESC LIMIT 1),
'Spam', '{}'),

-- Folders for jane.smith@yahoo.com
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'jane.smith@yahoo.com' ORDER BY created_at DESC LIMIT 1),
'Inbox', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'jane.smith@yahoo.com' ORDER BY created_at DESC LIMIT 1),
'Sent', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'jane.smith@yahoo.com' ORDER BY created_at DESC LIMIT 1),
'Trash', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'jane.smith@yahoo.com' ORDER BY created_at DESC LIMIT 1),
'Archives', '{}'),

-- Folders for robert.jones@outlook.com
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'robert.jones@outlook.com' ORDER BY created_at DESC LIMIT 1),
'Inbox', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'robert.jones@outlook.com' ORDER BY created_at DESC LIMIT 1),
'Sent', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'robert.jones@outlook.com' ORDER BY created_at DESC LIMIT 1),
'Drafts', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'robert.jones@outlook.com' ORDER BY created_at DESC LIMIT 1),
'Important', '{}'),

-- Folders for lucy.wang@company.com
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'lucy.wang@company.com' ORDER BY created_at DESC LIMIT 1),
'Inbox', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'lucy.wang@company.com' ORDER BY created_at DESC LIMIT 1),
'Sent', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'lucy.wang@company.com' ORDER BY created_at DESC LIMIT 1),
'Trash', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'lucy.wang@company.com' ORDER BY created_at DESC LIMIT 1),
'Projects', '{}'),

-- Folders for ahmed.ali@aol.com
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'ahmed.ali@aol.com' ORDER BY created_at DESC LIMIT 1),
'Inbox', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'ahmed.ali@aol.com' ORDER BY created_at DESC LIMIT 1),
'Sent', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'ahmed.ali@aol.com' ORDER BY created_at DESC LIMIT 1),
'Trash', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'ahmed.ali@aol.com' ORDER BY created_at DESC LIMIT 1),
'Archive', '{}'),

-- Folders for claudia.martinez@icloud.com
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'claudia.martinez@icloud.com' ORDER BY created_at DESC LIMIT 1),
'Inbox', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'claudia.martinez@icloud.com' ORDER BY created_at DESC LIMIT 1),
'Sent', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'claudia.martinez@icloud.com' ORDER BY created_at DESC LIMIT 1),
'Trash', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'claudia.martinez@icloud.com' ORDER BY created_at DESC LIMIT 1),
'VIP', '{}'),

-- Folders for david.kim@protonmail.com
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'david.kim@protonmail.com' ORDER BY created_at DESC LIMIT 1),
'Inbox', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'david.kim@protonmail.com' ORDER BY created_at DESC LIMIT 1),
'Sent', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'david.kim@protonmail.com' ORDER BY created_at DESC LIMIT 1),
'Drafts', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'david.kim@protonmail.com' ORDER BY created_at DESC LIMIT 1),
'Spam', '{}'),

-- Folders for maria.gonzalez@zoho.com
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'maria.gonzalez@zoho.com' ORDER BY created_at DESC LIMIT 1),
'Inbox', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'maria.gonzalez@zoho.com' ORDER BY created_at DESC LIMIT 1),
'Sent', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'maria.gonzalez@zoho.com' ORDER BY created_at DESC LIMIT 1),
'Trash', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'maria.gonzalez@zoho.com' ORDER BY created_at DESC LIMIT 1),
'Archives', '{}'),

-- Folders for paul.brown@fastmail.com
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'paul.brown@fastmail.com' ORDER BY created_at DESC LIMIT 1),
'Inbox', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'paul.brown@fastmail.com' ORDER BY created_at DESC LIMIT 1),
'Sent', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'paul.brown@fastmail.com' ORDER BY created_at DESC LIMIT 1),
'Drafts', '{}'),
(lower(hex(randomblob(16))),
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1),
(SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'paul.brown@fastmail.com' ORDER BY created_at DESC LIMIT 1),
'Junk', '{}');


INSERT INTO ur_ingest_session_imap_acct_folder_message (
    ur_ingest_session_imap_acct_folder_message_id, 
    ingest_session_id, 
    ingest_imap_acct_folder_id,
    uniform_resource_id, 
    message, 
    message_id, 
    subject, 
    "from", 
    cc, 
    bcc, 
    status, 
    date, 
    email_references
) VALUES 
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Hey John, here is the report you asked for.', 'msg-0001', 'Monthly Report', 'manager@example.com', '[]', '[]', '["UNREAD"]', '2024-08-01', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Dont forget the meeting tomorrow at 9 AM.', 'msg-0002', 'Meeting Reminder', 'teamlead@example.com', '[]', '[]', '["UNREAD", "IMPORTANT"]', '2024-08-01', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com') ORDER BY created_at DESC LIMIT 1),
'attachment_resource_id_2', 'Please find the attached invoice.', 'msg-0003', 'Invoice August', 'billing@example.com', '[]', '[]', '["READ"]', '2024-08-01', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Happy Birthday, John! Wishing you all the best.', 'msg-0004', 'Happy Birthday!', 'friends@example.com', '["jane@example.com"]', '[]', '["UNREAD"]', '2024-08-02', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com') ORDER BY created_at DESC LIMIT 1),
'attachment_resource_id_3', 'Here is the project proposal.', 'msg-0005', 'Project Proposal', 'client@example.com', '[]', '[]', '["READ"]', '2024-08-02', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Please review the attached contract.', 'msg-0006', 'Contract Review', 'legal@example.com', '[]', '[]', '["UNREAD"]', '2024-08-03', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Can we reschedule our meeting?', 'msg-0007', 'Meeting Reschedule', 'colleague@example.com', '[]', '[]', '["UNREAD"]', '2024-08-04', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Please confirm your subscription.', 'msg-0008', 'Subscription Confirmation', 'newsletters@example.com', '[]', '[]', '["UNREAD", "PROMOTION"]', '2024-08-05', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'John, here is your weekly update.', 'msg-0009', 'Weekly Update', 'updates@example.com', '[]', '[]', '["READ"]', '2024-08-06', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Reminder: Your bill is due.', 'msg-0010', 'Billing Reminder', 'billing@example.com', '[]', '[]', '["UNREAD"]', '2024-08-06', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Your flight has been confirmed.', 'msg-0011', 'Flight Confirmation', 'travel@example.com', '[]', '[]', '["READ"]', '2024-08-07', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Invitation to the annual conference.', 'msg-0012', 'Conference Invitation', 'events@example.com', '[]', '[]', '["UNREAD"]', '2024-08-08', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Your account statement is ready.', 'msg-0013', 'Account Statement', 'bank@example.com', '[]', '[]', '["READ"]', '2024-08-08', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'New job opening in your area.', 'msg-0014', 'Job Opening', 'careers@example.com', '[]', '[]', '["UNREAD"]', '2024-08-09', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Thank you for your purchase.', 'msg-0015', 'Purchase Confirmation', 'store@example.com', '[]', '[]', '["READ"]', '2024-08-09', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Your subscription has been renewed.', 'msg-0016', 'Subscription Renewal', 'services@example.com', '[]', '[]', '["UNREAD"]', '2024-08-10', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Reminder: Doctors appointment on Monday.', 'msg-0017', 'Appointment Reminder', 'clinic@example.com', '[]', '[]', '["UNREAD", "IMPORTANT"]', '2024-08-11', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Your password has been reset.', 'msg-0018', 'Password Reset', 'support@example.com', '[]', '[]', '["READ"]', '2024-08-11', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'John, please review the attached document.', 'msg-0019', 'Document Review', 'colleague@example.com', '["boss@example.com"]', '[]', '["UNREAD"]', '2024-08-12', '[]'),
(lower(hex(randomblob(16))), 
(SELECT ur_ingest_session_id FROM ur_ingest_session ORDER BY created_at DESC LIMIT 1), 
(SELECT ur_ingest_session_imap_acct_folder_id FROM ur_ingest_session_imap_acct_folder WHERE folder_name = 'Inbox' AND ingest_account_id = (SELECT ur_ingest_session_imap_account_id FROM ur_ingest_session_imap_account WHERE email = 'john.doe@gmail.com') ORDER BY created_at DESC LIMIT 1),
NULL, 'Congratulations on your promotion!', 'msg-0020', 'Promotion', 'hr@example.com', '[]', '[]', '["READ"]', '2024-08-12', '[]');


